[package]
name = "graph-chain-substreams"
version = "0.27.0"
edition = "2021"

[build-dependencies]
tonic-build = { version = "0.7.2", features = ["prost"] }

[dependencies]
async-stream = "0.3"
envconfig = "0.10.0"
futures = "0.1.21"
http = "0.2.4"
jsonrpc-core = "18.0.0"
graph = { path = "../../graph" }
lazy_static = "1.2.0"
serde = "1.0"
prost = "0.10.4"
prost-types = "0.10.1"
dirs-next = "2.0"
anyhow = "1.0"
tiny-keccak = "1.5.0"
hex = "0.4.3"
semver = "1.0.12"

itertools = "0.10.3"

[dev-dependencies]
graph-core = { path = "../../core" }
tokio = { version = "1", features = ["full"]}
