[package]
name = "graph-mock"
version = "0.16.1"
edition = "2018"

[dependencies]
failure = "0.1.6"
futures = "0.1.21"
graphql-parser = "0.2.3"
graph = { path = "../graph" }
graph-graphql = { path = "../graphql" }
rand = "0.6.1"
