[package]
name = "graph-mock"
version = "0.19.2"
edition = "2018"

[dependencies]
failure = "0.1.7"
futures = "0.1.21"
graphql-parser = "0.2.3"
graph = { path = "../graph" }
graph-graphql = { path = "../graphql" }
mockall = "0.8"
rand = "0.6.1"
