[package]
name = "graph-mock"
version = "0.14.0"
edition = "2018"

[dependencies]
failure = "0.1.2"
futures = "0.1.21"
graphql-parser = "0.2.0"
graph = { path = "../graph" }
graph-graphql = { path = "../graphql" }
rand = "0.6.1"
