[package]
name = "thegraph"
version = "0.1.0"

[dependencies]
ethabi = "5.1"
ethereum-types = "0.3"
futures = "0.1.21"
graphql-parser = "0.2.1"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
slog = "2.2.3"
slog-async = "2.3.0"
slog-term = "2.4.0"
tokio = "0.1.6"
tokio-core = "0.1.17"
