[package]
name = "thegraph"
version = "0.1.0"

[dependencies]
futures = "0.1.21"
graphql-parser = "0.2.0"
serde = "1.0"
slog = "2.2.3"
slog-async = "2.3.0"
slog-term = "2.4.0"
tokio = "0.1.6"
tokio-core = "0.1.17"