[package]
name = "bus-google"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
google-cloud-pubsub = "0.9.0"
google-cloud-googleapis = "0.6.0"
serde = "1.0"
graph = { path = "../../graph" }
