[package]
name = "graph-chain-ethereum"
version = "0.26.0"
edition = "2021"

[dependencies]
envconfig = "0.10.0"
futures = "0.1.21"
http = "0.2.4"
jsonrpc-core = "18.0.0"
graph = { path = "../../graph" }
lazy_static = "1.2.0"
mockall = "0.9.1"
serde = "1.0"
prost = "0.10.4"
prost-types = "0.10.1"
dirs-next = "2.0"
anyhow = "1.0"
tiny-keccak = "1.5.0"
hex = "0.4.3"
semver = "1.0.9"

itertools = "0.10.3"

graph-runtime-wasm = { path = "../../runtime/wasm" }
graph-runtime-derive = { path = "../../runtime/derive" }

[dev-dependencies]
graph-core = { path = "../../core" }
test-store = { path = "../../store/test-store" }
base64 = "0.13.0"

[build-dependencies]
tonic-build = { version = "0.7.2", features = ["prost"] }
