[package]
name = "graph-server-json-rpc"
version.workspace = true
edition.workspace = true

[dependencies]
axum = { workspace = true }
graph = { path = "../../graph" }
serde = { workspace = true }
serde_json = { workspace = true }
slog = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
