[package]
name = "graph-server-json-rpc"
version = "0.4.0"

[dependencies]
graph = { path = "../../graph" }
graph-graphql = { path = "../../graphql" }
jsonrpc-http-server = { git = "https://github.com/paritytech/jsonrpc" }
serde = "1.0"
serde_derive = "1.0"
