[package]
name = "graph-server-json-rpc"
version = "0.28.0"
edition = "2021"

[dependencies]
graph = { path = "../../graph" }
jsonrpsee = { version = "0.15.1", features = ["http-server"] }
serde = "1.0"
