[package]
name = "graph-server-json-rpc"
version = "0.13.2"
edition = "2018"

[dependencies]
graph = { path = "../../graph" }
jsonrpc-http-server = { git = "https://github.com/paritytech/jsonrpc" }
lazy_static = "1.2.0"
serde = "1.0"
