[package]
name = "graph-server-index-node"
version = "0.26.0"
edition = "2021"

[dependencies]
blake3 = "1.0"
either = "1.6.1"
futures = "0.3.4"
graph = { path = "../../graph" }
graph-graphql = { path = "../../graphql" }
graph-chain-ethereum = { path = "../../chain/ethereum" }
graph-chain-near = { path = "../../chain/near" }
graph-chain-tendermint = { path = "../../chain/tendermint" }
graphql-parser = "0.4.0"
http = "0.2"
hyper = "0.14"
lazy_static = "1.2.0"
serde = "1.0"
