[package]
name = "graph-server-index-node"
version = "0.22.0"
edition = "2018"

[dependencies]
futures = "0.3.4"
graph = { path = "../../graph" }
graph-graphql = { path = "../../graphql" }
graphql-parser = "0.3"
http = "0.2"
hyper = "0.13"
serde = "1.0"
