[package]
name = "graph-server-index-node"
version = "0.16.1"
edition = "2018"

[dependencies]
futures = "0.1.21"
graph = { path = "../../graph" }
graph-graphql = { path = "../../graphql" }
graphql-parser = "0.2.3"
http = "0.1.5"
hyper = "0.12.35"
lazy_static = "1.2.0"
serde = "1.0"
