[package]
name = "graph-server-index-node"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = { workspace = true }
blake3 = "1.8"
graph = { path = "../../graph" }
graph-graphql = { path = "../../graphql" }
graph-chain-ethereum = { path = "../../chain/ethereum" }
graph-chain-near = { path = "../../chain/near" }
git-testament = { workspace = true }
