[package]
name = "graph-graphql"
version = "0.16.1"
edition = "2018"

[dependencies]
graph = { path = "../graph" }
graphql-parser = "0.2.3"
indexmap = "1.2"
Inflector = "0.11.3"
lazy_static = "1.2.0"
uuid = { version = "0.8.1", features = ["v4"] }

[dev-dependencies]
pretty_assertions = "0.6.1"
test-store = { path = "../store/test-store" }
