[package]
name = "graph-graphql"
version = "0.21.1"
edition = "2018"

[dependencies]
crossbeam = "0.8"
futures01 = { package="futures", version="0.1.29" }
graph = { path = "../graph" }
graphql-parser = "0.3"
indexmap = "1.6"
Inflector = "0.11.3"
lazy_static = "1.2.0"
uuid = { version = "0.8.1", features = ["v4"] }
stable-hash = { git = "https://github.com/graphprotocol/stable-hash" }
once_cell = "1.4.1"
defer = "0.1"
parking_lot = "0.11"
anyhow = "1.0"

[dev-dependencies]
pretty_assertions = "0.6.1"
test-store = { path = "../store/test-store" }
