[package]
name = "graph-graphql"
version = "0.11.0"
edition = "2018"

[dependencies]
graph = { path = "../graph" }
graphql-parser = "0.2.0"
indexmap = "1.0"
Inflector = "0.11.3"
lazy_static = "1.2.0"
uuid = { version = "0.7.2", features = ["v4"] }

[dev-dependencies]
pretty_assertions = "0.5.1"
test-store = { path = "../store/test-store" }
