[package]
name = "graph-graphql"
version = "0.25.0"
edition = "2018"

[dependencies]
crossbeam = "0.8"
futures01 = { package="futures", version="0.1.29" }
graph = { path = "../graph" }
graphql-parser = "0.4.0"
indexmap = "1.7"
Inflector = "0.11.3"
lazy_static = "1.2.0"
stable-hash = { git = "https://github.com/graphprotocol/stable-hash" }
once_cell = "1.9.0"
defer = "0.1"
parking_lot = "0.11"
anyhow = "1.0"

[dev-dependencies]
pretty_assertions = "1.0.0"
test-store = { path = "../store/test-store" }
graph-chain-ethereum = { path = "../chain/ethereum" }
