[package]
name = "test-store"
version.workspace = true
edition.workspace = true
authors = ["Leonardo Yvens <leoyvens@gmail.com>"]
description = "Provides static store instance for tests."

[dependencies]
graph-graphql = { path = "../../graphql" }
graph-node = { path = "../../node" }
graph = { path = "../../graph" }
graph-store-postgres = { path = "../postgres" }
graph-chain-ethereum = { path = "../../chain/ethereum" }
lazy_static = "1.5"
hex-literal = "0.4"
diesel = { workspace = true }
prost-types = { workspace = true }

[dev-dependencies]
hex = "0.4.3"
pretty_assertions = "1.4.0"
serde_json = { workspace = true }
