[package]
name = "graph-runtime-wasm"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = "0.1.50"
ethabi = "17.2"
hex = "0.4.3"
graph = { path = "../../graph" }
bs58 = "0.4.0"
graph-runtime-derive = { path = "../derive" }
semver = "1.0.23"
uuid = { version = "1.10.0", features = ["v4"] }
anyhow = "1.0"
never = "0.1"

wasmtime.workspace = true
wasm-instrument = { version = "0.2.0", features = ["std", "sign_ext"] }

# AssemblyScript uses sign extensions
parity-wasm = { version = "0.45", features = ["std", "sign_ext"] }
