[package]
name = "graph-runtime-wasm"
version = "0.16.1"
edition = "2018"

[dependencies]
ethabi = { git = "https://github.com/graphprotocol/ethabi.git", branch = "graph-patches" }
futures = "0.1.21"
hex = "0.4.0"
graph = { path = "../../graph" }
graph-graphql = { path = "../../graphql" }
wasmi = "0.5.1"
pwasm-utils = "0.11"
bs58 = "0.3.0"
graph-runtime-derive = { path = "../derive" }
semver = "0.9.0"
parity-wasm = "0.40"
lazy_static = "1.4"
uuid = { version = "0.8.1", features = ["v4"] }

[dev-dependencies]
graphql-parser = "0.2.3"
graph-core = { path = "../../core" }
graph-mock = { path = "../../mock" }
# We're using the latest ipfs-api for the HTTPS support that was merged in
# https://github.com/ferristseng/rust-ipfs-api/commit/55902e98d868dcce047863859caf596a629d10ec
# but has not been released yet.
ipfs-api = { git = "https://github.com/ferristseng/rust-ipfs-api", branch = "master", features = ["hyper-tls"] }
