[package]
name = "thegraph-runtime-wasm"
version = "0.1.0"

[dependencies]
ethabi = "5.1.1"
ethereum-types = "0.3"
futures = "0.1.21"
hex = "0.3.2"
nan-preserving-float = "0.1.0"
slog = "2.2.3"
tokio-core = "0.1.6"
thegraph = { path = "../../thegraph" }
uuid = { version = "0.6", features = ["v4"] }
wasmi = "0.3"
web3 = { git = "https://github.com/tomusdrw/rust-web3" }

[dev-dependencies]
graphql-parser = "0.2.0"
parity-wasm = "0.31"
