[package]
name = "graph-runtime-wasm"
version = "0.17.1"
edition = "2018"

[dependencies]
async-trait = "0.1.29"
ethabi = { git = "https://github.com/graphprotocol/ethabi.git", branch = "master" }
futures = "0.1.21"
hex = "0.4.2"
graph = { path = "../../graph" }
graph-graphql = { path = "../../graphql" }
wasmi = "0.5.1"
pwasm-utils = "0.11"
bs58 = "0.3.0"
graph-runtime-derive = { path = "../derive" }
semver = "0.9.0"
parity-wasm = "0.40"
lazy_static = "1.4"
uuid = { version = "0.8.1", features = ["v4"] }
strum = "0.18.0"
strum_macros = "0.18.0"
bytes = "0.5"

[dev-dependencies]
graphql-parser = "0.2.3"
graph-core = { path = "../../core" }
graph-mock = { path = "../../mock" }
test-store = { path = "../../store/test-store" }
ipfs-api = { version = "0.7.1", features = ["hyper-tls"] }
graph-chain-arweave = { path = "../../chain/arweave" }
