[package]
name = "graph-runtime-wasm"
version = "0.12.0"
edition = "2018"

[dependencies]
# We would like to switch to upstream master once https://github.com/paritytech/ethabi/pull/145
# is merged.
# But, graph-patches also contains Jannis' https://github.com/paritytech/ethabi/pull/140 PR
# to ethabi. Which we believe will not get merged. For now, we shall deviate from ethabi,
# but long term we want to avoid forking off ethabi if possible
ethabi = { git = "https://github.com/graphprotocol/ethabi.git", branch = "graph-patches" }
futures = "0.1.21"
hex = "0.3.2"
graph = { path = "../../graph" }
tiny-keccak = "1.4.2"
wasmi = "0.4"
pwasm-utils = "0.6.1"
bs58 = "0.2.2"
graph-runtime-derive = { path = "../derive" }
semver = "0.9.0"

[dev-dependencies]
graphql-parser = "0.2.0"
parity-wasm = "0.31"
graph-mock = { path = "../../mock" }
# We're using the latest ipfs-api for the HTTPS support that was merged in
# https://github.com/ferristseng/rust-ipfs-api/commit/55902e98d868dcce047863859caf596a629d10ec
# but has not been released yet.
ipfs-api = { git = "https://github.com/ferristseng/rust-ipfs-api", branch = "master", features = ["hyper-tls"] }
