[package]
name = "graph-node"
version = "0.24.2"
edition = "2018"
default-run = "graph-node"

[[bin]]
name = "graph-node"
path = "src/main.rs"

[[bin]]
name = "graphman"
path = "src/bin/manager.rs"

[dependencies]
clap = "2.33.3"
env_logger = "0.9.0"
git-testament = "0.2"
graphql-parser = "0.3"
futures = { version = "0.3.1", features = ["compat"] }
lazy_static = "1.2.0"
url = "2.2.1"
crossbeam-channel = "0.5.1"
graph = { path = "../graph" }
graph-core = { path = "../core" }
graph-chain-ethereum = { path = "../chain/ethereum" }
graph-chain-near = { path = "../chain/near" }
graph-graphql = { path = "../graphql" }
graph-runtime-wasm = { path = "../runtime/wasm" }
graph-server-http = { path = "../server/http" }
graph-server-index-node = { path = "../server/index-node" }
graph-server-json-rpc = { path = "../server/json-rpc"}
graph-server-websocket = { path = "../server/websocket" }
graph-server-metrics = { path = "../server/metrics" }
graph-store-postgres = { path = "../store/postgres" }
regex = "1.5.4"
serde = { version = "1.0.126", features = ["derive", "rc"] }
serde_regex = "1.1.0"
structopt = { version = "0.3.25", features = ["wrap_help"] }
toml = "0.5.7"
shellexpand = "2.1.0"
diesel = "1.4.8"
fail = "0.4"
http = "0.1.21" # must be compatible with the version rust-web3 uses

[dev-dependencies]
assert_cli = "0.6"
