[package]
name = "graph-node"
version = "0.6.0"
edition = "2018"

[dependencies]
clap = "2.31.2"
env_logger = "0.5.10"
futures = "0.1.21"
graphql-parser = "0.2.1"
http = "0.1"
ipfs-api = "0.5.0-alpha2"
itertools = "0.7"
lazy_static = "1.2.0"
sentry = "0.15.1"
url = "1.7.1"
graph = { path = "../graph" }
graph-core = { path = "../core" }
graph-datasource-ethereum = { path = "../datasource/ethereum" }
graph-mock = { path = "../mock" }
graph-runtime-wasm = { path = "../runtime/wasm" }
graph-server-http = { path = "../server/http" }
graph-server-json-rpc = { path = "../server/json-rpc"}
graph-server-websocket = { path = "../server/websocket" }
graph-store-postgres = { path = "../store/postgres" }

[dev-dependencies]
assert_cli = "0.6"
