[package]
name = "graph-server-metrics"
version = "0.22.0"
edition = "2018"

[dependencies]
futures = "0.1.21"
graph = { path = "../../graph" }
http = "0.2"
hyper = "0.13"
lazy_static = "1.2.0"
serde = "1.0"
