[package]
name = "graph-server-metrics"
version = "0.25.1"
edition = "2021"

[dependencies]
futures = "0.1.21"
graph = { path = "../../graph" }
http = "0.2"
hyper = { version = "0.14", features = ["server"] }
lazy_static = "1.2.0"
serde = "1.0"
