[package]
name = "graph-store-postgres"
version = "0.16.1"
edition = "2018"

[dependencies]
derive_more = { version = "0.15.0" }
diesel = { version = "1.4.3", features = ["postgres", "serde_json", "numeric", "r2d2"] }
# We use diesel-dynamic-schema straight from git as the project has not
# made a release as a crate yet
diesel-dynamic-schema = { git = "https://github.com/diesel-rs/diesel-dynamic-schema", rev="a8ec4fb1" }
diesel-derive-enum = { version = "0.4", features = ["postgres"] }
diesel_migrations = "1.3.0"
failure = "0.1.6"
fallible-iterator = "0.1.4"
futures = "0.1.21"
graph = { path = "../../graph" }
graph-graphql = { path = "../../graphql" }
graphql-parser = "0.2.3"
Inflector = "0.11.3"
lazy_static = "1.1"
lru_time_cache = "0.9"
postgres = "0.15.2"
serde = "1.0"
uuid = { version = "0.8.1", features = ["v4"] }

[dev-dependencies]
graphql-parser = "0.2.3"
hex = "0.4.0"
parity-wasm = "0.40"
test-store = { path = "../test-store" }
hex-literal = "0.2"
graph-mock = { path = "../../mock" }
