[package]
name = "graph-store-postgres"
version = "0.6.0"
edition = "2018"

[dependencies]
diesel = { version = "1.3.2", features = ["postgres", "serde_json", "numeric", "r2d2"] }
diesel_migrations = "1.3.0"
failure = "0.1.2"
fallible-iterator = "0.1.4"
futures = "0.1.21"
graph = { path = "../../graph" }
graph-graphql = { path = "../../graphql" }
lru_time_cache = "0.8"
postgres = "0.15.2"
serde = "1.0"
uuid = { version = "0.7.2", features = ["v4"] }

[dev-dependencies]
graphql-parser = "0.2.0"
test-store = { path = "../test-store" }
lazy_static = "1.1"
hex = "0.3.2"
