[package]
name = "graph-store-postgres"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = { workspace = true }
blake3 = "1.8"
chrono = { workspace = true }
deadpool = { workspace = true }
derive_more = { version = "2.1.1", features = ["full"] }
diesel = { workspace = true }
diesel-async = { workspace = true }
diesel-dynamic-schema = { workspace = true }
diesel-derive-enum = { workspace = true }
diesel_derives = { workspace = true }
diesel_migrations = { workspace = true }
fallible-iterator = "0.3.0"
graph = { path = "../../graph" }
graphman-store = { workspace = true }
Inflector = { workspace = true }
lazy_static = "1.5"
lru_time_cache = "0.11"
postgres = "0.19.1"
openssl = { version = "0.10.75", features = ["vendored"] }
postgres-openssl = "0.5.2"
rand.workspace = true
serde = { workspace = true }
serde_json = { workspace = true }
stable-hash_legacy = { git = "https://github.com/graphprotocol/stable-hash", branch = "old", package = "stable-hash" }
tokio = { workspace = true }
tokio-stream = { workspace = true }
anyhow = "1.0.101"
git-testament = "0.2.6"
itertools = "0.14.0"
hex = "0.4.3"
pretty_assertions = "1.4.1"
sqlparser = { workspace = true }
thiserror = { workspace = true }
serde_yaml.workspace = true

[dev-dependencies]
clap.workspace = true

[lints]
workspace = true
