[package]
name = "graph-store-postgres"
version = "0.18.0"
edition = "2018"

[dependencies]
async-trait = "0.1.36"
blake3 = "0.3.5"
derive_more = { version = "0.99.9" }
diesel = { version = "1.4.3", features = ["postgres", "serde_json", "numeric", "r2d2"] }
# We use diesel-dynamic-schema straight from git as the project has not
# made a release as a crate yet
diesel-dynamic-schema = { git = "https://github.com/diesel-rs/diesel-dynamic-schema", rev="a8ec4fb1" }
diesel-derive-enum = { version = "1.1", features = ["postgres"] }
diesel_migrations = "1.3.0"
failure = "0.1.7"
fallible-iterator = "0.1.4"
futures = "0.1.21"
graph = { path = "../../graph" }
graph-chain-ethereum = { path = "../../chain/ethereum" }
graph-graphql = { path = "../../graphql" }
graphql-parser = "0.2.3"
Inflector = "0.11.3"
lazy_static = "1.1"
lru_time_cache = "0.9"
# TODO: Use crates.io once a version >= 0.3.3 is published
# See also 92cd8019-0136-4011-96a0-40b3eec37f73
maybe-owned = { git = "https://github.com/rustonaut/maybe-owned", branch = "master" }
postgres = "0.15.2"
serde = "1.0"
uuid = { version = "0.8.1", features = ["v4"] }
stable-hash = { git = "https://github.com/graphprotocol/stable-hash" }

[dev-dependencies]
clap = "2.33.1"
graphql-parser = "0.2.3"
hex = "0.4.2"
test-store = { path = "../test-store" }
hex-literal = "0.2"
graph-mock = { path = "../../mock" }
