[package]
name = "graph-store-postgres"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = "0.1.50"
blake3 = "1.3"
derive_more = { version = "0.99.17" }
diesel = { version = "1.4.8", features = ["postgres", "serde_json", "numeric", "r2d2"] }
# We use diesel-dynamic-schema straight from git as the project has not
# made a release as a crate yet
diesel-dynamic-schema = { git = "https://github.com/diesel-rs/diesel-dynamic-schema", rev = "a8ec4fb1" }
diesel-derive-enum = { version = "1.1", features = ["postgres"] }
diesel_migrations = "1.3.0"
fallible-iterator = "0.2.0"
graph = { path = "../../graph" }
graph-core = { path = "../../core" }
graph-graphql = { path = "../../graphql" }
Inflector = "0.11.3"
lazy_static = "1.1"
lru_time_cache = "0.11"
maybe-owned = "0.3.4"
postgres = "0.19.1"
openssl = "0.10.45"
postgres-openssl = "0.5.0"
rand = "0.8.4"
serde = "1.0"
uuid = { version = "1.3.0", features = ["v4"] }
stable-hash_legacy = { version = "0.3.3", package = "stable-hash" }
diesel_derives = "1.4.1"
anyhow = "1.0.70"
git-testament = "0.2.4"
itertools = "0.10.5"
pin-utils = "0.1"
hex = "0.4.3"
pretty_assertions = "1.3.0"

[dev-dependencies]
futures = "0.3"
clap = "3.2.23"
graphql-parser = "0.4.0"
test-store = { path = "../test-store" }
hex-literal = "0.3"
graph-chain-ethereum = { path = "../../chain/ethereum" }
