[package]
name = "graph-store-postgres"
version = "0.25.1"
edition = "2021"

[dependencies]
async-trait = "0.1.50"
blake3 = "0.3.8"
derive_more = { version = "0.99.17" }
diesel = { version = "1.4.8", features = ["postgres", "serde_json", "numeric", "r2d2"] }
# We use diesel-dynamic-schema straight from git as the project has not
# made a release as a crate yet
diesel-dynamic-schema = { git = "https://github.com/diesel-rs/diesel-dynamic-schema", rev="a8ec4fb1" }
diesel-derive-enum = { version = "1.1", features = ["postgres"] }
diesel_migrations = "1.3.0"
fallible-iterator = "0.2.0"
futures = "0.1.21"
graph = { path = "../../graph" }
graph-graphql = { path = "../../graphql" }
graphql-parser = "0.4.0"
Inflector = "0.11.3"
lazy_static = "1.1"
lru_time_cache = "0.11"
maybe-owned = "0.3.4"
postgres = "0.19.1"
rand = "0.8.4"
serde = "1.0"
uuid = { version = "0.8.1", features = ["v4"] }
stable-hash = { git = "https://github.com/graphprotocol/stable-hash" }
diesel_derives = "1.4.1"
anyhow = "1.0.54"
git-testament = "0.2.0"
itertools = "0.10.3"
pin-utils = "0.1"
hex = "0.4.3"

[dev-dependencies]
clap = "2.34.0"
graphql-parser = "0.4.0"
test-store = { path = "../test-store" }
hex-literal = "0.3"
graph-chain-ethereum = { path = "../../chain/ethereum" }
graph-mock = { path = "../../mock" }
