[package]
name = "graph-store-postgres"
version = "0.1.0"

[dependencies]
bigdecimal = "0.0.11"
diesel = { version = "1.3.2", features = ["postgres", "serde_json", "numeric"] }
diesel_migrations = "1.3.0"
ethereum-types = "0.3"
diesel-dynamic-schema = { git = "https://github.com/diesel-rs/diesel-dynamic-schema" }
futures = "0.1.21"
serde_json = "1.0"
graph = { path = "../../graph" }

[dev-dependencies]
lazy_static = "1.1"
