[package]
name = "graph-server-http"
version = "0.1.0"

[dependencies]
futures = "0.1.21"
graphql-parser = "0.2.0"
http = "0.1.5"
hyper = { git = "https://github.com/hyperium/hyper", branch = "master" }
serde = "1.0"
serde_json = "1.0"
slog = "2.2.3"
graph = { path = "../../graph" }
graph-graphql = { path = "../../graphql" }
tokio = "0.1.6"
tokio-core = "0.1.17"
