[package]
name = "graph-server-http"
version = "0.16.1"
edition = "2018"

[dependencies]
futures = "0.1.21"
graphql-parser = "0.2.3"
http = "0.1.18"
hyper = "0.12.35"
serde = "1.0"
graph = { path = "../../graph" }
graph-graphql = { path = "../../graphql" }

[dev-dependencies]
graph-mock = { path = "../../mock" }
