[package]
name = "graph-server-http"
version = "0.25.1"
edition = "2021"

[dependencies]
futures = "0.1.21"
graphql-parser = "0.4.0"
http = "0.2"
hyper = "0.14"
serde = "1.0"
graph = { path = "../../graph" }
graph-graphql = { path = "../../graphql" }

[dev-dependencies]
graph-mock = { path = "../../mock" }
