[package]
name = "graph-server-http"
version = "0.19.2"
edition = "2018"

[dependencies]
failure = "0.1.7"
futures = "0.1.21"
graphql-parser = "0.2.3"
http = "0.2"
hyper = "0.13"
serde = "1.0"
graph = { path = "../../graph" }
graph-graphql = { path = "../../graphql" }

[dev-dependencies]
graph-mock = { path = "../../mock" }
