[package]
name = "graph-server-websocket"
version.workspace = true
edition.workspace = true

[dependencies]
futures = "0.1.23"
graph = { path = "../../graph" }
serde = { workspace = true }
serde_derive = { workspace = true }
tokio-tungstenite = "0.17"
uuid = { version = "1.6.1", features = ["v4"] }
