[package]
name = "graph-server-websocket"
version = "0.16.1"
edition = "2018"

[dependencies]
futures = "0.1.23"
graph = { path = "../../graph" }
graphql-parser = "0.2.1"
graph-graphql = { path = "../../graphql" }
hyper = "0.12.7"
lazy_static = "1.2.0"
serde = "1.0"
serde_derive = "1.0"
tokio-tungstenite = "0.6"
uuid = { version = "0.7.2", features = ["v4"] }
